name: lych
description: Basic program functions for db access etc.
version: 1.0.0

environment:
  sdk: '^3.5.0'


dependencies:
  flutter:
    sdk: flutter
  http: any
  reflectable: any

dev_dependencies:
  lints: any
  test: any
  build_runner: any
  built_value_generator: any
