name: lych
description: Basic program functions for db access etc.
version: 1.0.0

environment:
  sdk: '>3.0.0'


dependencies:
  flutter:
    sdk: flutter
  http: any
  reflectable: any

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  build_runner: any
  built_value_generator: any
